### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by miguelbautista** [nmwsharp/learned-triangulation#1]
Hi,

First of all I would like to congratulate you on the paper! I think this contribution is great. I was planning to use this implementation strictly for research purposes (eg. comparing results and obviously cite your paper) but there's no license attached to the repo. Would you mind adding one?

Thanks!

**Comment by nmwsharp** [comment]
Thanks! Lack of license was a total oversight :) MIT license now added in ad9f4bd
